### ISSUE TITLE
Make new command to rerun .pick with the last "negative" choice exluded

### ISSUE THREAD

**Issue by raek** [serpis/pynik#20]
When asked to .pick between some choices the bot may currently reply "I wouldn't pick X". Implement a command to rerun the .pick command with the same choices, but with X removed.

Suggested name: .so...

**Comment by serpis** [comment]
Hm I wonder how much state we must save between calls. It would be annoying to keep data for every channel and user. Perhaps only the last per channel?

**Comment by serpis** [comment]
Fixed by 9350e1b957f91a2a98f590d5306abd694b79fad3.
You can now run .pick again after a negative pick response to rerun with remaining choices
